In [4]:
import pandas as pd
import numpy as np
from numpy import array
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame

In [5]:
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [6]:
def main():

    for i in range(1, 8) : 

        problem = i
        if problem ==1:
            traindata = np.loadtxt("Lazer/train.txt")
            testdata= np.loadtxt("Lazer/test.txt")
            name= "Lazer"
        if problem ==2:
            traindata = np.loadtxt(  "Sunspot/train.txt")
            testdata= np.loadtxt( "Sunspot/test.txt")
            name= "Sunspot"
        if problem ==3:
            traindata = np.loadtxt("Mackey/train.txt")
            testdata= np.loadtxt("Mackey/test.txt")  
            name= "Mackey"
        if problem ==4:
            traindata = np.loadtxt("Lorenz/train.txt")
            testdata= np.loadtxt("Lorenz/test.txt")  
            name= "Lorenz"
        if problem ==5:
            traindata = np.loadtxt( "Rossler/train.txt")
            testdata= np.loadtxt( "Rossler/test.txt")
            name= "Rossler"
        if problem ==6:
            traindata = np.loadtxt("Henon/train.txt")
            testdata= np.loadtxt("Henon/test.txt")
            name= "Henon"
        if problem ==7:
            traindata = np.loadtxt("ACFinance/train.txt") 
            testdata= np.loadtxt("ACFinance/test.txt")
            name= "ACFinance"
        
        print(name)
        print(traindata)
        print(testdata)
        
        train = traindata[0,0:3]
        for x in traindata:
            train = np.concatenate((train, x[3:5]))
        test = testdata[0,0:3]
        for x in testdata:
            test = np.concatenate((test, x[3:5]))


        # choose a number of time steps
        n_steps_in, n_steps_out = 5,10

        # split into samples
        train_X, train_Y = split_sequence(train, n_steps_in, n_steps_out)

        train = np.concatenate((train_X, train_Y), axis=1)
        train = pd.DataFrame(train, columns = ['Input1', 'Input2','Input3','Input4','Input5','Output1','Output2','Output3','Output4','Output5','Output6','Output7','Output8','Output9','Output10'])
        print(train.head())

        # summarize the data
        for i in range(len(train_X)):
            print(train_X[i], train_Y[i])

        # split into samples
        test_X, test_Y= split_sequence(test, n_steps_in, n_steps_out)

        test = np.concatenate((test_X, test_Y), axis=1)
        test = pd.DataFrame(test, columns = ['Input1', 'Input2','Input3','Input4','Input5','Output1','Output2','Output3','Output4','Output5','Output6','Output7','Output8','Output9','Output10'])
        print(test.head())

        # summarize the data
        for i in range(len(test_X)):
            print(test_X[i], test_Y[i])

        if problem ==1:
            train.to_csv('Lazer/train1.csv')
            test.to_csv('Lazer/test1.csv')
        if problem ==2:
            train.to_csv('Sunspot/train1.csv')
            test.to_csv('Sunspot/test1.csv')
        if problem ==3:
            train.to_csv('Mackey/train1.csv')
            test.to_csv('Mackey/test1.csv')
        if problem ==4:
            train.to_csv('Lorenz/train1.csv')
            test.to_csv('Lorenz/test1.csv')
        if problem ==5:
            train.to_csv('Rossler/train1.csv')
            test.to_csv('Rossler/test1.csv')
        if problem ==6:
            train.to_csv('Henon/train1.csv')
            test.to_csv('Henon/test1.csv')
        if problem ==7:
            train.to_csv('ACFinance/train1.csv')
            test.to_csv('ACFinance/test1.csv') 
        
if __name__ == "__main__": main()

Lazer
[[0.335938  0.550781  0.371094  0.160156  0.0859375]
 [0.371094  0.160156  0.0859375 0.0820312 0.125    ]
 [0.0859375 0.0820312 0.125     0.28125   0.539062 ]
 ...
 [0.0234375 0.046875  0.1875    0.753906  0.671875 ]
 [0.1875    0.753906  0.671875  0.152344  0.0429688]
 [0.671875  0.152344  0.0429688 0.0273438 0.0234375]]
[[0.0625    0.335938  0.996094  0.417969  0.0742188]
 [0.996094  0.417969  0.0742188 0.03125   0.0195312]
 [0.0742188 0.03125   0.0195312 0.015625  0.0117188]
 [0.0195312 0.015625  0.0117188 0.0078125 0.0078125]
 [0.0117188 0.0078125 0.0078125 0.0273438 0.0898438]
 [0.0078125 0.0273438 0.0898438 0.03125   0.0234375]
 [0.0898438 0.03125   0.0234375 0.03125   0.0625   ]
 [0.0234375 0.03125   0.0625    0.128906  0.222656 ]
 [0.0625    0.128906  0.222656  0.253906  0.21875  ]
 [0.222656  0.253906  0.21875   0.179688  0.179688 ]
 [0.21875   0.179688  0.179688  0.210938  0.25     ]
 [0.179688  0.210938  0.25      0.257812  0.230469 ]
 [0.25      0.257812  0.230469  0.

[0.25      0.0703125 0.0390625 0.03125   0.0507812] [0.144531  0.578125  0.761719  0.226562  0.0625    0.0351562 0.03125
 0.0390625 0.113281  0.515625 ]
[0.0703125 0.0390625 0.03125   0.0507812 0.144531 ] [0.578125  0.761719  0.226562  0.0625    0.0351562 0.03125   0.0390625
 0.113281  0.515625  0.859375 ]
[0.0390625 0.03125   0.0507812 0.144531  0.578125 ] [0.761719  0.226562  0.0625    0.0351562 0.03125   0.0390625 0.113281
 0.515625  0.859375  0.261719 ]
[0.03125   0.0507812 0.144531  0.578125  0.761719 ] [0.226562  0.0625    0.0351562 0.03125   0.0390625 0.113281  0.515625
 0.859375  0.261719  0.0585938]
[0.0507812 0.144531  0.578125  0.761719  0.226562 ] [0.0625    0.0351562 0.03125   0.0390625 0.113281  0.515625  0.859375
 0.261719  0.0585938 0.03125  ]
[0.144531 0.578125 0.761719 0.226562 0.0625  ] [0.0351562 0.03125   0.0390625 0.113281  0.515625  0.859375  0.261719
 0.0585938 0.03125   0.0234375]
[0.578125  0.761719  0.226562  0.0625    0.0351562] [0.03125   0.0390625 0.113281

[0.179688 0.351562 0.46875  0.320312 0.164062] [0.113281 0.109375 0.175781 0.34375  0.484375 0.335938 0.167969 0.105469
 0.105469 0.160156]
[0.351562 0.46875  0.320312 0.164062 0.113281] [0.109375 0.175781 0.34375  0.484375 0.335938 0.167969 0.105469 0.105469
 0.160156 0.324219]
[0.46875  0.320312 0.164062 0.113281 0.109375] [0.175781 0.34375  0.484375 0.335938 0.167969 0.105469 0.105469 0.160156
 0.324219 0.492188]
[0.320312 0.164062 0.113281 0.109375 0.175781] [0.34375  0.484375 0.335938 0.167969 0.105469 0.105469 0.160156 0.324219
 0.492188 0.355469]
[0.164062 0.113281 0.109375 0.175781 0.34375 ] [0.484375 0.335938 0.167969 0.105469 0.105469 0.160156 0.324219 0.492188
 0.355469 0.175781]
[0.113281 0.109375 0.175781 0.34375  0.484375] [0.335938 0.167969 0.105469 0.105469 0.160156 0.324219 0.492188 0.355469
 0.175781 0.105469]
[0.109375 0.175781 0.34375  0.484375 0.335938] [0.167969 0.105469 0.105469 0.160156 0.324219 0.492188 0.355469 0.175781
 0.105469 0.101562]
[0.175781 0.34375  0

 0.0784314 0.0831643 0.0831643]
[0.136579 0.130494 0.127113 0.123056 0.118323] [0.11021   0.096687  0.0811359 0.0736984 0.07167   0.0736984 0.0784314
 0.0831643 0.0831643 0.0791075]
[0.130494 0.127113 0.123056 0.118323 0.11021 ] [0.096687  0.0811359 0.0736984 0.07167   0.0736984 0.0784314 0.0831643
 0.0831643 0.0791075 0.0804598]
[0.127113 0.123056 0.118323 0.11021  0.096687] [0.0811359 0.0736984 0.07167   0.0736984 0.0784314 0.0831643 0.0831643
 0.0791075 0.0804598 0.086545 ]
[0.123056  0.118323  0.11021   0.096687  0.0811359] [0.0736984 0.07167   0.0736984 0.0784314 0.0831643 0.0831643 0.0791075
 0.0804598 0.086545  0.0912779]
[0.118323  0.11021   0.096687  0.0811359 0.0736984] [0.07167   0.0736984 0.0784314 0.0831643 0.0831643 0.0791075 0.0804598
 0.086545  0.0912779 0.096687 ]
[0.11021   0.096687  0.0811359 0.0736984 0.07167  ] [0.0736984 0.0784314 0.0831643 0.0831643 0.0791075 0.0804598 0.086545
 0.0912779 0.096687  0.0987153]
[0.096687  0.0811359 0.0736984 0.07167   0.0736984] [0

[0.138607 0.129141 0.120352 0.114943 0.112914] [0.11021   0.102096  0.0926302 0.0845166 0.0791075 0.0777552 0.0784314
 0.0811359 0.0791075 0.076403 ]
[0.129141 0.120352 0.114943 0.112914 0.11021 ] [0.102096  0.0926302 0.0845166 0.0791075 0.0777552 0.0784314 0.0811359
 0.0791075 0.076403  0.0791075]
[0.120352 0.114943 0.112914 0.11021  0.102096] [0.0926302 0.0845166 0.0791075 0.0777552 0.0784314 0.0811359 0.0791075
 0.076403  0.0791075 0.0797836]
[0.114943  0.112914  0.11021   0.102096  0.0926302] [0.0845166 0.0791075 0.0777552 0.0784314 0.0811359 0.0791075 0.076403
 0.0791075 0.0797836 0.0730223]
[0.112914  0.11021   0.102096  0.0926302 0.0845166] [0.0791075 0.0777552 0.0784314 0.0811359 0.0791075 0.076403  0.0791075
 0.0797836 0.0730223 0.07167  ]
[0.11021   0.102096  0.0926302 0.0845166 0.0791075] [0.0777552 0.0784314 0.0811359 0.0791075 0.076403  0.0791075 0.0797836
 0.0730223 0.07167   0.0797836]
[0.102096  0.0926302 0.0845166 0.0791075 0.0777552] [0.0784314 0.0811359 0.0791075 0.0

[0.414469 0.377958 0.361731 0.372549 0.402975] [0.423935 0.421907 0.417174 0.406356 0.384719 0.371873 0.381339 0.402975
 0.422583 0.424611]
[0.377958 0.361731 0.372549 0.402975 0.423935] [0.421907 0.417174 0.406356 0.384719 0.371873 0.381339 0.402975 0.422583
 0.424611 0.40906 ]
[0.361731 0.372549 0.402975 0.423935 0.421907] [0.417174 0.406356 0.384719 0.371873 0.381339 0.402975 0.422583 0.424611
 0.40906  0.377282]
[0.372549 0.402975 0.423935 0.421907 0.417174] [0.406356 0.384719 0.371873 0.381339 0.402975 0.422583 0.424611 0.40906
 0.377282 0.347532]
[0.402975 0.423935 0.421907 0.417174 0.406356] [0.384719 0.371873 0.381339 0.402975 0.422583 0.424611 0.40906  0.377282
 0.347532 0.340095]
[0.423935 0.421907 0.417174 0.406356 0.384719] [0.371873 0.381339 0.402975 0.422583 0.424611 0.40906  0.377282 0.347532
 0.340095 0.340771]
[0.421907 0.417174 0.406356 0.384719 0.371873] [0.381339 0.402975 0.422583 0.424611 0.40906  0.377282 0.347532 0.340095
 0.340771 0.342123]
[0.417174 0.406356 0.

 0.473    0.486455]
[0.430378 0.43387  0.434354 0.432555 0.429304] [0.4256   0.422642 0.421777 0.42432  0.431203 0.442554 0.457302 0.473
 0.486455 0.495165]
[0.43387  0.434354 0.432555 0.429304 0.4256  ] [0.422642 0.421777 0.42432  0.431203 0.442554 0.457302 0.473    0.486455
 0.495165 0.4984  ]
[0.434354 0.432555 0.429304 0.4256   0.422642] [0.421777 0.42432  0.431203 0.442554 0.457302 0.473    0.486455 0.495165
 0.4984   0.49702 ]
[0.432555 0.429304 0.4256   0.422642 0.421777] [0.42432  0.431203 0.442554 0.457302 0.473    0.486455 0.495165 0.4984
 0.49702  0.492605]
[0.429304 0.4256   0.422642 0.421777 0.42432 ] [0.431203 0.442554 0.457302 0.473    0.486455 0.495165 0.4984   0.49702
 0.492605 0.486771]
[0.4256   0.422642 0.421777 0.42432  0.431203] [0.442554 0.457302 0.473    0.486455 0.495165 0.4984   0.49702  0.492605
 0.486771 0.48088 ]
[0.422642 0.421777 0.42432  0.431203 0.442554] [0.457302 0.473    0.486455 0.495165 0.4984   0.49702  0.492605 0.486771
 0.48088  0.47592 ]
[0.421

[0.488518 0.491247 0.493937 0.495385 0.494066] [0.488349 0.477187 0.460965 0.441412 0.420679 0.400483 0.381925 0.365551
 0.351466 0.339432]
[0.491247 0.493937 0.495385 0.494066 0.488349] [0.477187 0.460965 0.441412 0.420679 0.400483 0.381925 0.365551 0.351466
 0.339432 0.328982]
[0.493937 0.495385 0.494066 0.488349 0.477187] [0.460965 0.441412 0.420679 0.400483 0.381925 0.365551 0.351466 0.339432
 0.328982 0.319546]
[0.495385 0.494066 0.488349 0.477187 0.460965] [0.441412 0.420679 0.400483 0.381925 0.365551 0.351466 0.339432 0.328982
 0.319546 0.310599]
[0.494066 0.488349 0.477187 0.460965 0.441412] [0.420679 0.400483 0.381925 0.365551 0.351466 0.339432 0.328982 0.319546
 0.310599 0.301791]
[0.488349 0.477187 0.460965 0.441412 0.420679] [0.400483 0.381925 0.365551 0.351466 0.339432 0.328982 0.319546 0.310599
 0.301791 0.293034]
[0.477187 0.460965 0.441412 0.420679 0.400483] [0.381925 0.365551 0.351466 0.339432 0.328982 0.319546 0.310599 0.301791
 0.293034 0.284547]
[0.460965 0.441412 0

 0.401766 0.415041]
[0.2056   0.196521 0.191776 0.192871 0.201339] [0.218032 0.242298 0.271789 0.303255 0.333671 0.360892 0.383735 0.401766
 0.415041 0.423903]
[0.196521 0.191776 0.192871 0.201339 0.218032] [0.242298 0.271789 0.303255 0.333671 0.360892 0.383735 0.401766 0.415041
 0.423903 0.428855]
[0.191776 0.192871 0.201339 0.218032 0.242298] [0.271789 0.303255 0.333671 0.360892 0.383735 0.401766 0.415041 0.423903
 0.428855 0.430496]
[0.192871 0.201339 0.218032 0.242298 0.271789] [0.303255 0.333671 0.360892 0.383735 0.401766 0.415041 0.423903 0.428855
 0.430496 0.4295  ]
[0.201339 0.218032 0.242298 0.271789 0.303255] [0.333671 0.360892 0.383735 0.401766 0.415041 0.423903 0.428855 0.430496
 0.4295   0.426634]
[0.218032 0.242298 0.271789 0.303255 0.333671] [0.360892 0.383735 0.401766 0.415041 0.423903 0.428855 0.430496 0.4295
 0.426634 0.4228  ]
[0.242298 0.271789 0.303255 0.333671 0.360892] [0.383735 0.401766 0.415041 0.423903 0.428855 0.430496 0.4295   0.426634
 0.4228   0.419082]
[0

 0.310623 0.298679]
[0.402298 0.397891 0.392966 0.387503 0.381485] [0.374887 0.367687 0.359861 0.351386 0.342239 0.332404 0.321867 0.310623
 0.298679 0.286054]
[0.397891 0.392966 0.387503 0.381485 0.374887] [0.367687 0.359861 0.351386 0.342239 0.332404 0.321867 0.310623 0.298679
 0.286054 0.272785]
[0.392966 0.387503 0.381485 0.374887 0.367687] [0.359861 0.351386 0.342239 0.332404 0.321867 0.310623 0.298679 0.286054
 0.272785 0.25893 ]
[0.387503 0.381485 0.374887 0.367687 0.359861] [0.351386 0.342239 0.332404 0.321867 0.310623 0.298679 0.286054 0.272785
 0.25893  0.244575]
[0.381485 0.374887 0.367687 0.359861 0.351386] [0.342239 0.332404 0.321867 0.310623 0.298679 0.286054 0.272785 0.25893
 0.244575 0.229833]
[0.374887 0.367687 0.359861 0.351386 0.342239] [0.332404 0.321867 0.310623 0.298679 0.286054 0.272785 0.25893  0.244575
 0.229833 0.214855]
[0.367687 0.359861 0.351386 0.342239 0.332404] [0.321867 0.310623 0.298679 0.286054 0.272785 0.25893  0.244575 0.229833
 0.214855 0.199828]
[

[0.515065 0.516437 0.517871 0.519384 0.520993] [0.522716 0.524571 0.526578 0.528757 0.531129 0.533716 0.536544 0.53964
 0.543033 0.546754]
[0.516437 0.517871 0.519384 0.520993 0.522716] [0.524571 0.526578 0.528757 0.531129 0.533716 0.536544 0.53964  0.543033
 0.546754 0.550838]
[0.517871 0.519384 0.520993 0.522716 0.524571] [0.526578 0.528757 0.531129 0.533716 0.536544 0.53964  0.543033 0.546754
 0.550838 0.555323]
[0.519384 0.520993 0.522716 0.524571 0.526578] [0.528757 0.531129 0.533716 0.536544 0.53964  0.543033 0.546754 0.550838
 0.555323 0.560251]
[0.520993 0.522716 0.524571 0.526578 0.528757] [0.531129 0.533716 0.536544 0.53964  0.543033 0.546754 0.550838 0.555323
 0.560251 0.565667]
[0.522716 0.524571 0.526578 0.528757 0.531129] [0.533716 0.536544 0.53964  0.543033 0.546754 0.550838 0.555323 0.560251
 0.565667 0.571618]
[0.524571 0.526578 0.528757 0.531129 0.533716] [0.536544 0.53964  0.543033 0.546754 0.550838 0.555323 0.560251 0.565667
 0.571618 0.578159]
[0.526578 0.528757 0.

[0.711316 0.728595 0.746899 0.766139 0.78617 ] [0.806784 0.827699 0.84855  0.868887 0.888177 0.905818 0.921167 0.933568
 0.942408 0.947161]
[0.728595 0.746899 0.766139 0.78617  0.806784] [0.827699 0.84855  0.868887 0.888177 0.905818 0.921167 0.933568 0.942408
 0.947161 0.947446]
[0.746899 0.766139 0.78617  0.806784 0.827699] [0.84855  0.868887 0.888177 0.905818 0.921167 0.933568 0.942408 0.947161
 0.947446 0.943064]
[0.766139 0.78617  0.806784 0.827699 0.84855 ] [0.868887 0.888177 0.905818 0.921167 0.933568 0.942408 0.947161 0.947446
 0.943064 0.934028]
[0.78617  0.806784 0.827699 0.84855  0.868887] [0.888177 0.905818 0.921167 0.933568 0.942408 0.947161 0.947446 0.943064
 0.934028 0.920564]
[0.806784 0.827699 0.84855  0.868887 0.888177] [0.905818 0.921167 0.933568 0.942408 0.947161 0.947446 0.943064 0.934028
 0.920564 0.903095]
[0.827699 0.84855  0.868887 0.888177 0.905818] [0.921167 0.933568 0.942408 0.947161 0.947446 0.943064 0.934028 0.920564
 0.903095 0.882203]
[0.84855  0.868887 0

[0.638462 0.654447 0.66911  0.682282 0.693807] [0.703542 0.711363 0.717161 0.720846 0.722351 0.721629 0.718658 0.713437
 0.705992 0.696368]
[0.654447 0.66911  0.682282 0.693807 0.703542] [0.711363 0.717161 0.720846 0.722351 0.721629 0.718658 0.713437 0.705992
 0.696368 0.684637]
[0.66911  0.682282 0.693807 0.703542 0.711363] [0.717161 0.720846 0.722351 0.721629 0.718658 0.713437 0.705992 0.696368
 0.684637 0.67089 ]
[0.682282 0.693807 0.703542 0.711363 0.717161] [0.720846 0.722351 0.721629 0.718658 0.713437 0.705992 0.696368 0.684637
 0.67089  0.655238]
[0.693807 0.703542 0.711363 0.717161 0.720846] [0.722351 0.721629 0.718658 0.713437 0.705992 0.696368 0.684637 0.67089
 0.655238 0.637812]
[0.703542 0.711363 0.717161 0.720846 0.722351] [0.721629 0.718658 0.713437 0.705992 0.696368 0.684637 0.67089  0.655238
 0.637812 0.618761]
[0.711363 0.717161 0.720846 0.722351 0.721629] [0.718658 0.713437 0.705992 0.696368 0.684637 0.67089  0.655238 0.637812
 0.618761 0.598249]
[0.717161 0.720846 0.

 0.586231 0.630503]
[0.154883 0.176108 0.200914 0.229105 0.260448] [0.294676 0.331485 0.370546 0.411498 0.453956 0.497515 0.541752 0.586231
 0.630503 0.674117]
[0.176108 0.200914 0.229105 0.260448 0.294676] [0.331485 0.370546 0.411498 0.453956 0.497515 0.541752 0.586231 0.630503
 0.674117 0.716618]
[0.200914 0.229105 0.260448 0.294676 0.331485] [0.370546 0.411498 0.453956 0.497515 0.541752 0.586231 0.630503 0.674117
 0.716618 0.757552]
[0.229105 0.260448 0.294676 0.331485 0.370546] [0.411498 0.453956 0.497515 0.541752 0.586231 0.630503 0.674117 0.716618
 0.757552 0.796467]
[0.260448 0.294676 0.331485 0.370546 0.411498] [0.453956 0.497515 0.541752 0.586231 0.630503 0.674117 0.716618 0.757552
 0.796467 0.832913]
[0.294676 0.331485 0.370546 0.411498 0.453956] [0.497515 0.541752 0.586231 0.630503 0.674117 0.716618 0.757552 0.796467
 0.832913 0.866438]
[0.331485 0.370546 0.411498 0.453956 0.497515] [0.541752 0.586231 0.630503 0.674117 0.716618 0.757552 0.796467 0.832913
 0.866438 0.896563]


[0.575051 0.546696 0.526375 0.509637 0.494315] [0.479519 0.46497  0.450648 0.43664  0.423071 0.410076 0.397793 0.386356
 0.375893 0.366522]
[0.546696 0.526375 0.509637 0.494315 0.479519] [0.46497  0.450648 0.43664  0.423071 0.410076 0.397793 0.386356 0.375893
 0.366522 0.358354]
[0.526375 0.509637 0.494315 0.479519 0.46497 ] [0.450648 0.43664  0.423071 0.410076 0.397793 0.386356 0.375893 0.366522
 0.358354 0.351491]
[0.509637 0.494315 0.479519 0.46497  0.450648] [0.43664  0.423071 0.410076 0.397793 0.386356 0.375893 0.366522 0.358354
 0.351491 0.34602 ]
[0.494315 0.479519 0.46497  0.450648 0.43664 ] [0.423071 0.410076 0.397793 0.386356 0.375893 0.366522 0.358354 0.351491
 0.34602  0.342017]
[0.479519 0.46497  0.450648 0.43664  0.423071] [0.410076 0.397793 0.386356 0.375893 0.366522 0.358354 0.351491 0.34602
 0.342017 0.339545]
[0.46497  0.450648 0.43664  0.423071 0.410076] [0.397793 0.386356 0.375893 0.366522 0.358354 0.351491 0.34602  0.342017
 0.339545 0.338652]
[0.450648 0.43664  0.

 0.697148 0.488202]
[0.677084 0.619614 0.72518  0.505445 0.819041] [0.187019 0.302403 0.440544 0.672706 0.567877 0.777833 0.342585 0.697148
 0.488202 0.810021]
[0.619614 0.72518  0.505445 0.819041 0.187019] [0.302403 0.440544 0.672706 0.567877 0.777833 0.342585 0.697148 0.488202
 0.810021 0.213412]
[0.72518  0.505445 0.819041 0.187019 0.302403] [0.440544 0.672706 0.567877 0.777833 0.342585 0.697148 0.488202 0.810021
 0.213412 0.387731]
[0.505445 0.819041 0.187019 0.302403 0.440544] [0.672706 0.567877 0.777833 0.342585 0.697148 0.488202 0.810021 0.213412
 0.387731 0.595553]
[0.819041 0.187019 0.302403 0.440544 0.672706] [0.567877 0.777833 0.342585 0.697148 0.488202 0.810021 0.213412 0.387731
 0.595553 0.667176]
[0.187019 0.302403 0.440544 0.672706 0.567877] [0.777833 0.342585 0.697148 0.488202 0.810021 0.213412 0.387731 0.595553
 0.667176 0.624838]
[0.302403 0.440544 0.672706 0.567877 0.777833] [0.342585 0.697148 0.488202 0.810021 0.213412 0.387731 0.595553 0.667176
 0.624838 0.715105]


[0.661075 0.636636 0.696112 0.578682 0.776044] [0.351336 0.711512 0.458169 0.805371 0.220323 0.408113 0.620778 0.642933
 0.674228 0.625657]
[0.636636 0.696112 0.578682 0.776044 0.351336] [0.711512 0.458169 0.805371 0.220323 0.408113 0.620778 0.642933 0.674228
 0.625657 0.716079]
[0.696112 0.578682 0.776044 0.351336 0.711512] [0.458169 0.805371 0.220323 0.408113 0.620778 0.642933 0.674228 0.625657
 0.716079 0.529601]
[0.578682 0.776044 0.351336 0.711512 0.458169] [0.805371 0.220323 0.408113 0.620778 0.642933 0.674228 0.625657 0.716079
 0.529601 0.811601]
[0.776044 0.351336 0.711512 0.458169 0.805371] [0.220323 0.408113 0.620778 0.642933 0.674228 0.625657 0.716079 0.529601
 0.811601 0.220368]
[0.351336 0.711512 0.458169 0.805371 0.220323] [0.408113 0.620778 0.642933 0.674228 0.625657 0.716079 0.529601 0.811601
 0.220368 0.410121]
[0.711512 0.458169 0.805371 0.220323 0.408113] [0.620778 0.642933 0.674228 0.625657 0.716079 0.529601 0.811601 0.220368
 0.410121 0.622821]
[0.458169 0.805371 0

[0.804632 0.240559 0.468581 0.668328 0.584596] [0.762336 0.394165 0.76804  0.320209 0.652235 0.568784 0.771    0.363714
 0.729622 0.417439]
[0.240559 0.468581 0.668328 0.584596 0.762336] [0.394165 0.76804  0.320209 0.652235 0.568784 0.771    0.363714 0.729622
 0.417439 0.782618]
[0.468581 0.668328 0.584596 0.762336 0.394165] [0.76804  0.320209 0.652235 0.568784 0.771    0.363714 0.729622 0.417439
 0.782618 0.282531]
[0.668328 0.584596 0.762336 0.394165 0.76804 ] [0.320209 0.652235 0.568784 0.771    0.363714 0.729622 0.417439 0.782618
 0.282531 0.573339]
[0.584596 0.762336 0.394165 0.76804  0.320209] [0.652235 0.568784 0.771    0.363714 0.729622 0.417439 0.782618 0.282531
 0.573339 0.656489]
[0.762336 0.394165 0.76804  0.320209 0.652235] [0.568784 0.771    0.363714 0.729622 0.417439 0.782618 0.282531 0.573339
 0.656489 0.637416]
[0.394165 0.76804  0.320209 0.652235 0.568784] [0.771    0.363714 0.729622 0.417439 0.782618 0.282531 0.573339 0.656489
 0.637416 0.693547]
[0.76804  0.320209 0

 0.845736 0.847545]
[0.764083 0.764341 0.786304 0.802583 0.825064] [0.81938  0.812661 0.819897 0.831266 0.836951 0.840052 0.84987  0.845736
 0.847545 0.843928]
[0.764341 0.786304 0.802583 0.825064 0.81938 ] [0.812661 0.819897 0.831266 0.836951 0.840052 0.84987  0.845736 0.847545
 0.843928 0.850645]
[0.786304 0.802583 0.825064 0.81938  0.812661] [0.819897 0.831266 0.836951 0.840052 0.84987  0.845736 0.847545 0.843928
 0.850645 0.84031 ]
[0.802583 0.825064 0.81938  0.812661 0.819897] [0.831266 0.836951 0.840052 0.84987  0.845736 0.847545 0.843928 0.850645
 0.84031  0.837209]
[0.825064 0.81938  0.812661 0.819897 0.831266] [0.836951 0.840052 0.84987  0.845736 0.847545 0.843928 0.850645 0.84031
 0.837209 0.833333]
[0.81938  0.812661 0.819897 0.831266 0.836951] [0.840052 0.84987  0.845736 0.847545 0.843928 0.850645 0.84031  0.837209
 0.833333 0.834108]
[0.812661 0.819897 0.831266 0.836951 0.840052] [0.84987  0.845736 0.847545 0.843928 0.850645 0.84031  0.837209 0.833333
 0.834108 0.829715]
[

[0.473126 0.468475 0.474418 0.458398 0.426615] [0.452713 0.460982 0.426615 0.393281 0.367184 0.343153 0.321188 0.283979
 0.287339 0.341085]
[0.468475 0.474418 0.458398 0.426615 0.452713] [0.460982 0.426615 0.393281 0.367184 0.343153 0.321188 0.283979 0.287339
 0.341085 0.323256]
[0.474418 0.458398 0.426615 0.452713 0.460982] [0.426615 0.393281 0.367184 0.343153 0.321188 0.283979 0.287339 0.341085
 0.323256 0.278294]
[0.458398 0.426615 0.452713 0.460982 0.426615] [0.393281 0.367184 0.343153 0.321188 0.283979 0.287339 0.341085 0.323256
 0.278294 0.310853]
[0.426615 0.452713 0.460982 0.426615 0.393281] [0.367184 0.343153 0.321188 0.283979 0.287339 0.341085 0.323256 0.278294
 0.310853 0.304909]
[0.452713 0.460982 0.426615 0.393281 0.367184] [0.343153 0.321188 0.283979 0.287339 0.341085 0.323256 0.278294 0.310853
 0.304909 0.312661]
[0.460982 0.426615 0.393281 0.367184 0.343153] [0.321188 0.283979 0.287339 0.341085 0.323256 0.278294 0.310853 0.304909
 0.312661 0.294315]
[0.426615 0.393281 0